config/urls.py
from django.contrib import admin
from django.urls import path, include
from groups.views import home


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('student/', include('students.urls')),
    path('group/', include('groups.urls')),
    path('', include('teachers.urls')),
]

groups/urls.py
from django.urls import path
from . import views

app_name = 'groups'

urlpatterns = [
    path('', views.group_name, name='group_list'),
    path('create/', views.group_type, name='create'),
    path('detail/<int:pk>/', views.group_detail, name='detail'),
    path('delete/<int:pk>/', views.group_delete, name='delete'),
]

students/urls.py
from django.urls import path
from . import views

app_name = 'students'

urlpatterns = [
    path('', views.student_list, name='student_list'),
    path('craete', views.student_form, name='create'),
    path('detail/<int:pk>', views.student_detil, name='detail'),
    path('delete/<int:pk>', views.student_delete, name='delete'),
]

teachers/urls.py
from django.urls import path
from . import views

app_name = 'teachers'

urlpatterns = [
    path('list/', views.teacher_list, name='teacher_list'),
    path('create/', views.teacher_form, name='create'),
    path('detail/<int:pk>/', views.teacher_detail, name='detail'),
    path('delete/<int:pk>/', views.teacher_delete, name='delete')
]

groups/models.py
from django.db import models


class Groups(models.Model):
    group_name = models.CharField(max_length=100)
    group_type = models.CharField(max_length=100)

students/models.py
from django.db import models


class Student(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    age = models.PositiveIntegerField()
    email = models.EmailField(unique=True)

teachers/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator


class Teachers(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    age = models.PositiveIntegerField(
        validators=[MinValueValidator(0), MaxValueValidator(80)]
    )
    email = models.EmailField(unique=True)

groups/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Groups


def home(request):
    return render(request, 'index.html')


def group_name(request):
    groups = Groups.objects.all()
    ctx = {'groups': groups}
    return render(request, 'groups/groups-list.html', ctx)


def group_type(request):
    if request.method == 'POST':
        group_name = request.POST.get('group_name')
        group_type = request.POST.get('group_type')
        if group_name and group_type:
            Groups.objects.create(
                group_name=group_name,
                group_type=group_type
            )
            return redirect('groups:group_list')
    return render(request, 'groups/groups-form.html')


def group_detail(request, pk):
    groups = get_object_or_404(Groups, pk=pk)
    ctx = {'groups': groups}
    return render(request, 'groups/groups-detail.html', ctx)


def group_delete(request, pk):
    groups = get_object_or_404(Groups, pk=pk)
    groups.delete()
    return redirect('groups:group_list')

students/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Student


def student_list(request):
    students = Student.objects.all()
    ctx = {'students': students}
    return render(request, 'students/student-list.html', ctx)


def student_form(request):
    if request.method == 'POST':
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        age = request.POST.get('age')
        email = request.POST.get('email')

        if (first_name and last_name and email):
            Student.objects.create(
                first_name=first_name,
                last_name=last_name,
                age=age,
                email=email
            )
            return redirect('students:student_list')
    return render(request, 'students/student-form.html')


def student_detil(request, pk):
    students = get_object_or_404(Student, pk=pk)
    ctx = {'students': students}
    return render(request, 'students/student-detail.html', ctx)


def student_delete(request, pk):
    person = get_object_or_404(Student, pk=pk)
    person.delete()
    return redirect('students:student_list')

teachers/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Teachers


def teacher_list(request):
    teachers = Teachers.objects.all()
    ctx = {'teachers': teachers}
    return render(request, 'teachers/teachers-list.html', ctx)


def teacher_form(request):
    if request.method == 'POST':
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        age = request.POST.get('age')
        email = request.POST.get('email')

        if first_name and last_name and email:
            Teachers.objects.create(
                first_name=first_name,
                last_name=last_name,
                age=age,
                email=email

            )
            return redirect('teachers:teacher_list')
    return render(request, 'teachers/teachers-form.html')


def teacher_detail(request, pk):
    teacher = get_object_or_404(Teachers, pk=pk)
    ctx = {'teachers': teacher}
    return render(request, 'teachers/teachers-detail.html', ctx)


def teacher_delete(request, pk):
    person = get_object_or_404(Teachers, pk=pk)
    person.delete()
    return redirect('teachers:teacher_list')

templates/groups/groups-detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ groups.group_name }} {{ groups.group_type }}</title>
</head>
<body>
    <h1>{{ groups.group_name }} {{ groups.group_type }}</h1>
    <h3>Details:</h3>
    <a href="{% url 'groups:delete' pk=groups.pk %}">Delete</a><br>
    <a href="{% url 'groups:group_list' %}">Back to list</a>
</body>
</html>

templates/groups/groups-form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create Groups</title>
</head>
<body>
    <h1>Create Gorups</h1>
    <form method="post">
        {% csrf_token %}
        <label for="group_name">Groups Name</label><br>
        <input type="text" name="group_name" id="group_name" required><br>

        <label for="group_type">Groups Type</label><br>
        <input type="text" name="group_type" id="group_type"><br>

        <input type="submit" value="Create groups">

        <a href="{% url 'home' %}">Back to Home</a><br>
        <a href="{% url 'groups:group_list' %}">Back to List</a><br>
    </form>
</body>
</html>

templates/groups/groups-list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Groups List</title>
</head>
<body>
    <h1>Groups List</h1>
    <a href="{% url 'groups:create' %}">Create Groups</a>
    {% for groups in groups %}
        <a href="{% url 'groups:detail' pk=groups.pk %}"><h3>{{ groups.group_name }} {{ groups.group_type }}</h3></a>
    {% empty %}
        <h3>Not found</h3>
    {% endfor %}

    <a href="{% url 'home' %}">Back to Home</a><br>
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

</head>
<body>
<a href="{% url 'groups:group_list' %}">Group List</a><br>
<a href="{% url 'students:student_list' %}">Students List</a><br>
<a href="{% url 'teachers:teacher_list' %}">Teachaer List</a><br>
</body>
</html>

templates/students/student-detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ students.title }}</title>
</head>
<body>
    <h1>{{ students.first_name }} {{ students.last_name }}</h1>
    <h3>Details:</h3>
    <h3>Age: {{ students.age }}</h3>
    <h3>Email: {{ students.email }}</h3>
    <a href="{% url 'students:delete' pk=students.pk %}">Delete</a><br>
    <a href="{% url 'students:student_list' %}">Back to list</a>
</body>
</html>

templates/students/student-form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create Student</title>
</head>
<body>
    <h1>Create Student</h1>
    <form method="post">
        {% csrf_token %}
        <label for="first_name">First Name</label><br>
        <input type="text" name="first_name" id="first_name" required><br>

        <label for="last_name">Last Name</label><br>
        <input type="text" name="last_name" id="last_name"><br>

        <label for="age">Age</label><br>
        <input type="number" name="age" id="age"><br>

        <label for="email">Email</label><br>
        <input type="text" name="email" id="email"><br>
        <input type="submit" value="Create students">

    </form>
</body>
</html>

templates/students/student-list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Student List</title>
</head>
<body>
    <h1>Student List</h1>
    <a href="{% url 'students:create' %}">Create Student</a>
    {% for students in students %}
        <a href="{% url 'students:detail' pk=students.pk %}"><h3>{{ students.first_name }} {{ students.last_name }}</h3></a>
    {% empty %}
        <h3>Not found</h3>
    {% endfor %}

    <a href="{% url 'home' %}">Back to Home</a><br>
</body>
</html>

templates/teachers/teachers-detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ teachers.title }}</title>
</head>
<body>
    <h1>{{ teachers.first_name }} {{ teachers.last_name }}</h1>
    <h3>Details:</h3>
    <h3>Age: {{ teachers.age }}</h3>
    <h3>Email: {{ teachers.email }}</h3>
    <a href="{% url 'teachers:delete' pk=teachers.pk %}">Delete</a><br>
    <a href="{% url 'teachers:teacher_list' %}">Back to list</a><br><br>

</body>
</html>

templates/teachers/teachers-form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create Teacher</title>
</head>
<body>
    <h1>Create Teacher</h1>
    <form method="post">
        {% csrf_token %}
        <label for="first_name">First Name</label><br>
        <input type="text" name="first_name" id="first_name" required><br>

        <label for="last_name">Last Name</label><br>
        <input type="text" name="last_name" id="last_name"><br>

        <label for="age">Age</label><br>
        <input type="number" name="age" id="age"><br>

        <label for="email">Email</label><br>
        <input type="text" name="email" id="email"><br>
        <input type="submit" value="Create teachers">

    </form>

    <a href="{% url 'teachers:teacher_list' %}">Back to List</a>
<a href="{% url 'home' %}">Home</a>
</body>
</html>

templates/teachers/teachers-list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Teacher List</title>
</head>
<body>
    <h1>Teacher List</h1>
    <a href="{% url 'teachers:create' %}">Create Teacher</a>
    <a href="{% url 'home' %}">Home</a>

    {% for teachers in teachers %}
        <a href="{% url 'teachers:detail' pk=teachers.pk %}"><h3>{{ teachers.first_name }} {{ teachers.last_name }}</h3></a>
    {% empty %}
        <h3>Not found</h3>
    {% endfor %}

  <a href="{% url 'home' %}">Back to Home</a><br><br>

</body>
</html>